require("core/options")
require("core/lazy")

require("scripts/delete-buffer")
require("scripts/terminal")
require("scripts/files/smart-find")
local language = require("scripts/language")
language.setup()
-- local env_manager = require("scripts/env-manager/init")
-- env_manager.setup({})
